export enum Specialty {
  Cardiology = 'Cardiology',
  Dermatology = 'Dermatology',
  Endocrinology = 'Endocrinology',
  Gastroenterology = 'Gastroenterology',
  Neurology = 'Neurology',
  Orthopedics = 'Orthopedics',
  Pediatrics = 'Pediatrics',
  Psychiatry = 'Psychiatry',
  Surgery = 'Surgery',
  Allergist = 'Allergist',
  Anesthesiologist = 'Anesthesiologist',
  Biologist = 'Biologist',
  Surgeon = 'Surgeon',
  Dentist = 'Dentist',
  Sonographer = 'Sonographer',
  ENT = 'ENT (Otorhinolaryngologist)',
  Nutritionist = 'Nutritionist',
  Ophthalmologist = 'Ophthalmologist',
  Orthodontist = 'Orthodontist',
  Radiologist = 'Radiologist',
  GynecologistObstetrician = 'Gynecologist-Obstetrician',
  Other = 'Other',
}
